FROM docker:latest

WORKDIR /home/app

RUN echo "http://mirrors.aliyun.com/alpine/v3.16/main" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.16/community" >> /etc/apk/repositories

RUN apk add --no-cache --update nodejs npm yarn

